Criação pagina escolas
fablabjoinville/fablabjoinville.github.io pull request #46
Opened 2020-04-15 19:07 UTC by menderson

2020-04-21 16:29 UTC, murilooon requested changes
Ficou mto bom a página, achei super bonitinha. Precisamos apenas pensar em como fazer quando tivermos mais de uma oficina, além de Scratch, mas podemos deixar isso mais pra frente. Fiz comentários de coisas que precisa mudar pra ficar top o código.

PS: Não precisa ficar bad com as reviews, na Magrathea e no mercado de desenvolvimento a galera usa essa prática, sempre com o intuito de deixar o código simples, sem erros e de facil entendimento 💯

2020-04-21 16:29 UTC, murilooon commented on _includes/header.html
> +
Linha a mais aqui

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +        <p class="description">Aqui você encontra a apostila tutorial para seguir o passo a passo da contrução do jogo
```suggestion
        <p class="description">Aqui você encontra a apostila tutorial para seguir o passo a passo da construção do jogo
```

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +          <p id="text-schools">Conheça mais a <a href="">Proposta de Projeto</a>.</p>
Não entendi o que vai ter nesse link aqui

2020-04-21 16:29 UTC, murilooon commented on assets/stylesheets/main.scss
> +#photos-eschools{
```suggestion
#photos-schools{
```

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +            src="../../uploads/escolas/slides.png"></a>
você n precisa dessa tag <a> envolta da <img>. Ali embaixo tbm n precisa

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +        <h3 class="name"><a href="" target="_blank" rel="noopener">Apostila tutorial</a></h3>
falta colocar o link da apostila aqui, pode gerar um pdf da apostila, deixar na pasta do drive e colocar o link aqui.

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +        <p class="description">Aqui você encontra a apostila tutorial para seguir o passo a passo da contrução do jogo
```suggestion
        <p class="description">Aqui você encontra a apostila tutorial para seguir o passo a passo da construção do jogo
```

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +          <p>Arinor Vogelsanger</p>
Faz sentido usar listas em html aqui, com <li> e <ul>

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +              <td><img class="img-responsive tool-logo" width=115 height=115 src="/assets/images/escolas.png"></td>
Essa configurações da pra fazer igual falei antes também: width=115 height=115

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +            href="https://www.udesc.br/ceplan/noticia/cerca_de_300_alunos_da_rede_publica_foram_atendidos_por_projeto_de_programacao_da_udesc_joinville">
espaço desnecessário

2020-04-21 16:29 UTC, murilooon commented on escolas.html
> +</div>
é uma boa prática deixar uma linha a mais no fim de cada arquivo. Quando aparece esse simbolo vermelho é que faltou essa linha

2020-04-21 16:43 UTC, murilooon commented
Uma outra coisinha que observei aqui. Alguns textos que ficam ao lado da imagem em alguns casos ficam mais pra cima, não centralizados verticalmente. Tem alguns parametros em CSS que faciltiam bastante nesse caso. Se eu achar algum link eu mando pra ti

2020-04-22 22:05 UTC, menderson commented on escolas.html
> +          <p id="text-schools">Conheça mais a <a href="">Proposta de Projeto</a>.</p>
Esse link vai conter a proposta de projeto que é enviada pra diretora da escola. Contendo em detalhes os dados da oficina e respostas para perguntas frequentes

2020-04-23 20:21 UTC, murilooon approved these changes

2020-04-23 20:21 UTC, merged