Atualizações para deploy
fablabjoinville/fablabjoinville.github.io pull request #5
Opened 2017-04-09 19:10 UTC by diogotrentini

Boa tarde, pessoal!

Desculpe pelo PR longo e desconexo, mas aqui vão as últimas modificações pra nós colocarmos a página no ar.

Arrumei algumas coisas, atualizei alguns estilos (da página frontal e do blog - principalmente na listagem de posts - e no mobile), atualizei o thumbnail padrão para posts sem imagem. Além disso, melhorei alguns textos e a descrição dos planos. Podemos, obviamente, melhorar mais algumas coisas ainda, mas acho que esta versão já é "production ready". Aliás, farei deploy assim que fizermos o merge deste PR.

Algumas imagens (página frontal não possui "Próximos eventos" pois não temos nenhum confirmado, obviamente):

![front-desktop](https://cloud.githubusercontent.com/assets/3082268/24840107/6a2cffee-1d3d-11e7-88f7-68003d18a827.png)

----

![sobre-desktop](https://cloud.githubusercontent.com/assets/3082268/24840002/63fab3ac-1d3b-11e7-8772-0da8130b9b59.png)

----

![blog-desktop](https://cloud.githubusercontent.com/assets/3082268/24839998/63f73b46-1d3b-11e7-8ab7-b4a3fc839a50.png)

2017-04-09 22:10 UTC, romuloab requested changes
Obrigado por esse round de melhorias! Fiz alguns comentários pequenos. No geral está muito bom.

Se você achar que são desnecessários, não vou bloquear a publicação, mas gostaria de saber o motivo.

2017-04-09 22:10 UTC, romuloab commented on assets/stylesheets/main.scss
> +  }
Eu sei que fui eu que zuei com o tab-width, mas tem como normalizar para 2 espaços aqui também? Notei que você fez em outros arquivos, então seria legal voltar a ter apenas uma forma de indentar.

2017-04-09 22:10 UTC, romuloab commented on index.html
> +            <p>{{post.date | date: '%d/%m/%Y'}}</p>
Seria interessante manter consistência com a data relativa aqui? Não tenho opinião forte sobre isso.

2017-04-09 22:10 UTC, romuloab commented on _includes/footer.html
>          <p class="copyright">Fab Lab Joinville © 2017</p>
Minor: podia imprimir `2016-{{currentYear}}` (não sei como pegar a data atual no Jekyll -- a preguiça impera)

2017-04-10 23:05 UTC, diogotrentini commented on assets/stylesheets/main.scss
> +        width:calc(100% - 60px);
Posso usar `left: 0; right: 0`, acho que fica melhor. O que acha?

2017-04-10 23:07 UTC, diogotrentini commented on _layouts/blog.html
> +</article>
Achei que seria interessante ter algum tipo de jumbotron no blog, do mesmo modo que temos no "Sobre" - coisa simples, só uma introdução. Por isso criei um layout só pra o blog. As outras páginas (como os posts) não possuem uma introdução, então uso apenas o layout normal, sem jumbotron.

2017-04-10 23:09 UTC, diogotrentini commented on _includes/footer.html
>          <p class="copyright">Fab Lab Joinville © 2017</p>
:+1:

Usei `2016 - {{ site.time | date: '%Y' }}`

2017-04-10 23:11 UTC, diogotrentini commented on _includes/footer.html
> -        <p><a target="_blank" rel="noopener" href="https://github.com/fablabjoinville/fablabjoinville.github.io/blob/master/{{page.path}}">Editar esta página no Github</a></p>
Não faço questão de remover, mas imaginei que esse link seria um pouco confuso para pessoas não técnicas, lembrando que este site se comunica com vários tipos de pessoas. O que acha? Posso colocar de volta se discordar.

2017-04-10 23:44 UTC, diogotrentini commented on _includes/posts.html
> +    <span class="post-date ts">{{post.date | date: '%d/%m/%Y'}}</span>
Estava conversando com o @alfakini e achamos um pouco ruim quando a data fica no formato de "Há 163 dias". "Hoje" e "Ontem" até fica interessante, mas a partir disso acho que fica mais legível deixar em formato de data normal (o Medium faz mais ou menos assim, só ignorando o ano). Estava pensando em mudar o script do `_layouts/default.html` para retornar `str` [aqui](https://github.com/fablabjoinville/fablabjoinville.github.io/blob/master/_layouts/default.html#L25). O que acha?

2017-04-11 00:18 UTC, romuloab approved these changes
:+1:

2017-04-11 00:18 UTC, romuloab commented on _includes/posts.html
> +    <span class="post-date ts">{{post.date | date: '%d/%m/%Y'}}</span>
Pode ser!

2017-04-11 00:18 UTC, romuloab commented on _layouts/blog.html
> +</article>
Eu gosto de manter consistência, mas acho que é justificável

:+1:

2017-04-11 00:18 UTC, romuloab commented
Você comentou que quer mudar o script de data relativa, então vou deixar para você mesclar o PR.

2017-04-11 00:35 UTC, diogotrentini commented
Fiz algumas mudanças que o @alfakini pediu, e vamos fazer deploy! 😄

2017-04-11 00:36 UTC, merged

2017-04-11 12:47 UTC, romuloab commented
👏